:
	ghdl -a maq_estados.vhd
	ghdl -e maq_estados
	ghdl -a ula.vhd
	ghdl -e ula
	ghdl -a pc.vhd
	ghdl -e pc
	ghdl -a soma1_pc.vhd
	ghdl -e soma1_pc
	ghdl -a rom.vhd
	ghdl -e rom
	ghdl -a reg_16bits.vhd
	ghdl -e reg_16bits
	ghdl -a banco_reg.vhd
	ghdl -e banco_reg
	ghdl -a .vhd
	ghdl -e 
	ghdl -r  --wave=.ghw
	gtkwave .ghw